# Generated by Django 4.0.2 on 2022-03-20 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='images/profile')),
                ('facebook_url', models.CharField(blank=True, max_length=150, null=True)),
                ('website_url', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=150, null=True)),
                ('github_url', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
