# Generated by Django 4.0.2 on 2022-03-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_bio_profile_facebook_url_profile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
