# Generated by Django 4.0.7 on 2022-08-12 19:32

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
