# Generated by Django 4.1.7 on 2023-03-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_postcategory_alter_post_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="")),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("codebase", models.URLField(blank=True, null=True)),
                ("live_project", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
