# Generated by Django 4.1.7 on 2023-03-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_portfolioprojects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioprojects",
            name="image",
            field=models.ImageField(upload_to="images/projects"),
        ),
    ]
