# Generated by Django 4.1.7 on 2023-03-24 05:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_alter_portfolioprojects_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolioprojects",
            options={
                "verbose_name": "PortfolioProject",
                "verbose_name_plural": "PortfolioProject",
            },
        ),
    ]
