# Generated by Django 4.0.2 on 2022-03-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_category'),
        ('website', '0008_delete_category'),
    ]

    operations = [
    ]
