# Generated by Django 4.1.7 on 2023-03-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="linkedin_url",
            field=models.CharField(
                blank=True,
                default="https://www.linkedin.com",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="facebook_url",
            field=models.CharField(
                blank=True, default="https://facebook.com", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github_url",
            field=models.CharField(
                blank=True, default="https://github.com", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="instagram_url",
            field=models.CharField(
                blank=True, default="https://instagram.com", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter_url",
            field=models.CharField(
                blank=True, default="https://twitter.com", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website_url",
            field=models.CharField(
                blank=True, default="https://example.com", max_length=150, null=True
            ),
        ),
    ]
