# Generated by Django 4.1.7 on 2023-03-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "useraccounts",
            "0002_profile_linkedin_url_alter_profile_facebook_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
