# Generated by Django 4.1.7 on 2023-03-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useraccounts", "0003_customuser_linkedin_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="facebook_url",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github_url",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="instagram_url",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter_url",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website_url",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
